---
- hosts: node 
  roles:
    - selinux
    - ssh_authorized
    - yum
    - hostname
    - disk
    - mount

- hosts: manager
  roles:
    - docker
    - docker-swarm-init

- hosts: worker
  roles:
    - docker
    - docker-swarm-add-worker
